import "./globals.css";
import Footer from "@/components/commons/Footer";
import Header from "@/components/commons/Header";

export const metadata = {
  title: "Thaalia Eats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
