import "./globals.css";
import Footer from "@/components/commons/Footer";
import Header from "@/components/commons/Header";
import { Analytics } from "@vercel/analytics/react"
import AosInit from "@/components/commons/AosInit";

export const metadata = {
  title: "Thaalia Eats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        <AosInit />
        <Header />
        <main className="min-h-screen">{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
